CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    constraint pk_users PRIMARY KEY (id),
    constraint UQ_USER_EMAIL UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);
CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on timestamp without time zone,
    event_date timestamp without time zone,
    category bigint,
    confirmed_requests integer,
    annotation varchar(255),
    description varchar(4000),
    title varchar(255),
    initiator bigint,
    location bigint,
    paid boolean,
    participant_limit integer,
    published_on timestamp without time zone,
    request_moderation boolean,
    state varchar(64),
    views integer,
    constraint pk_events PRIMARY KEY (id),
    foreign key (initiator) references users(id)
);
