create table if not exists users (
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    email varchar(255) not null,
    constraint pk_users primary key (id),
    constraint uq_user_email unique (email)
);
create table if not exists categories (
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    constraint pk_categories primary key (id),
    constraint uq_category_name unique (name)
);
create table if not exists compilations (
    id bigint generated by default as identity not null,
    title varchar(255) not null,
    pinned boolean not null default false,
    constraint pk_compilations primary key (id)
);
create table if not exists requests (
    id bigint generated by default as identity not null,
    event_id bigint not null,
    requester_id bigint not null,
    status varchar(15) not null,
    created timestamp not null
);
create table if not exists events (
    id bigint generated by default as identity not null,
    created_on timestamp without time zone,
    published_on timestamp without time zone,
    event_date timestamp without time zone,
    annotation varchar(255),
    description varchar(4000),
    title varchar(255),
    state varchar(64),
    initiator bigint,
    category bigint,
    confirmed_requests integer,
    participant_limit integer,
    views integer,
    paid boolean,
    request_moderation boolean,
    location_lat numeric,
    location_lon numeric,
    constraint pk_events primary key (id),
    foreign key (initiator) references users(id)
);
